package com.paylite.wallet.controller;

import com.paylite.wallet.dto.AddMoneyRequest;
import com.paylite.wallet.dto.TransactionHistoryResponse;
import com.paylite.wallet.dto.TransferRequest;
import com.paylite.wallet.dto.TransferResponse;
import com.paylite.wallet.dto.WalletResponse;
import com.paylite.wallet.exception.IdempotencyKeyMissingException;
import com.paylite.wallet.service.TransferService;
import com.paylite.wallet.service.WalletService;

import jakarta.validation.Valid;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * HTTP endpoints for wallet operations.
 *
 * All endpoints require authentication. The current user (sender) is always
 * derived from the JWT — never trusted from URL or body — eliminating
 * IDOR vulnerabilities.
 */
@RestController
@RequestMapping("/api/wallets")
@RequiredArgsConstructor
@Slf4j
public class WalletController {

    private final WalletService walletService;
    private final TransferService transferService;

    /**
     * GET /api/wallets/me — get the current user's wallet.
     */
    @GetMapping("/me")
    public WalletResponse getMyWallet(@AuthenticationPrincipal UserDetails user) {
        log.debug("GET /api/wallets/me for email={}", user.getUsername());
        return walletService.getWalletByEmail(user.getUsername());
    }

    /**
     * GET /api/wallets/me/transactions — paginated transaction history.
     *
     * Returns all transfers involving the current user (sent + received),
     * newest first. Each item shows SENT/RECEIVED relative to the caller.
     *
     * Query params:
     *   page — zero-indexed page number (default 0)
     *   size — items per page (default 20)
     */
    @GetMapping("/me/transactions")
    public ResponseEntity<TransactionHistoryResponse> getTransactionHistory(
            @AuthenticationPrincipal UserDetails userDetails,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {

        log.debug("GET /api/wallets/me/transactions for email={} page={} size={}",
                userDetails.getUsername(), page, size);

        TransactionHistoryResponse history = walletService.getTransactionHistory(
                userDetails.getUsername(), page, size);

        return ResponseEntity.ok(history);
    }

    /**
     * POST /api/wallets/add-money — credit the current user's wallet.
     * In production, this would be triggered by a payment gateway webhook.
     */
    @PostMapping("/add-money")
    public WalletResponse addMoney(
            @AuthenticationPrincipal UserDetails user,
            @Valid @RequestBody AddMoneyRequest request) {

        log.debug("POST /api/wallets/add-money for email={} amount={}",
                user.getUsername(), request.getAmount());
        return walletService.addMoney(user.getUsername(), request);
    }

    /**
     * POST /api/wallets/transfer — transfer money from current user to another user.
     *
     * Requires Idempotency-Key header (UUID generated by client) — same header
     * + same body on retry returns the cached response without re-processing.
     *
     * Errors:
     *   400 — missing Idempotency-Key, invalid amount, self-transfer, insufficient balance
     *   404 — recipient not found
     *   409 — duplicate request with same key currently still processing
     */
    @PostMapping("/transfer")
    public TransferResponse transfer(
            @AuthenticationPrincipal UserDetails sender,
            @RequestHeader(value = "Idempotency-Key", required = false) String idempotencyKey,
            @Valid @RequestBody TransferRequest request) {

        if (idempotencyKey == null || idempotencyKey.isBlank()) {
            throw new IdempotencyKeyMissingException();
        }

        log.debug("POST /api/wallets/transfer sender={} recipient={} amount={} idempotencyKey={}",
                sender.getUsername(), request.getRecipientEmail(),
                request.getAmount(), idempotencyKey);

        return transferService.transfer(idempotencyKey, sender.getUsername(), request);
    }
}