server:
  port: 8081

spring:
  application:
    name: wallet-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3307/paylite_wallet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: paylite
    password: paylite_dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.paylite: DEBUG
    org.hibernate.SQL: DEBUG

paylite:
  jwt:
    secret: Tqk6ZTIA+54x7c9lf/Sl/io2Sfl54qUgtn+30uKnRH9e3+0krLZbozJP6EcXjr3HggSbgmgXY1nGPoHVdMbs/w==
    expiration-ms: 900000   # 15 minutes (15 * 60 * 1000)
    issuer: paylite-wallet-service